const GRID_TYPES = {
  CREATE_GRID: "CREATE_GRID",
  CREATE_MAZE: "CREATE_MAZE",
  FIND_PATH: "FIND_PATH",
  MARK_CELL_VISITED: "MARK_CELL_VISITED",
  MARK_SHORTEST_PATH: "MARK_SHORTEST_PATH",
};

export default GRID_TYPES;
